### ISSUE TITLE
Invalid version (inconsistent with the version tag)

### ISSUE THREAD

**Issue by 0mp** [uperf/uperf#12]
Hello :)

I'm porting uperf to FreeBSD at the moment and I find some inconsistencies from time to time.

One of them is a desynchronized version in source code and building toolchain files: https://github.com/uperf/uperf/search?utf8=%E2%9C%93&q=1.0-dev&type=

It says that the version is `1.0-dev` while the Git tag says it's `v1.0.6`.

**Comment by uperf** [comment]
Yeah we have not been super consistent about versioning.
