### ISSUE TITLE
Uperf is now a part of the FreeBSD Ports collection

### ISSUE THREAD

**Issue by 0mp** [uperf/uperf#14]
Just a heads up: Uperf has been successfully ported to FreeBSD and is now available as a binary package (`pkg install uperf`) and a port (`cd /usr/ports/benchmarks/uperf && make install clean`).

https://www.freshports.org/benchmarks/uperf

**Comment by uperf** [comment]
Wow that is nice!. I have updated the web page. Thanks

**Comment by 0mp** [comment]
@uperf 👍 Thank!
