### ISSUE TITLE
Consider adding support for TravisCI or CircleCI now that tests are working again

### ISSUE THREAD

**Issue by portante** [uperf/uperf#27]
Could we consider adding support for a CI environment like Travis or Circle?

**Comment by tuexen** [comment]
I normally do manual testing on FreeBSD, Linux, MacOS X, and Solaris. Not sure which OSes  are supported by Travis or Circle.

**Comment by portante** [comment]
For TravisCI it would be Ubuntu and MacOS X, I believe.  Not sure about Circle.

**Comment by tuexen** [comment]
Looking up, Cirrus does support FreeBSD VMs: https://cirrus-ci.org/guide/FreeBSD/
They also seem to support MacOS VMs and Linux Containers. So except for Solaris, they cover the supported OSes.

**Comment by mrbojangles3** [comment]
@portante, CI has been added via Github actions. It runs the tests from `make check`. If that is sufficient perhaps this issue can be closed?
