### ISSUE TITLE
Tagging source code

### ISSUE THREAD

**Issue by svetlemodry** [uperf/uperf#3]
Hi all,
would it be possible to implement tags onto the commits, so that downloading source code would be easier here?
See https://github.com/uperf/uperf/releases

Thanks!

**Comment by uperf** [comment]
yeah sure. Thanks for pointing it out

**Comment by svetlemodry** [comment]
Any ETA to implement the tags?
Cheers!

**Comment by uperf** [comment]
ok I tagged 1.0.6.

**Comment by svetlemodry** [comment]
Awesome, thanks!
