### ISSUE TITLE
Documentation [Blogs Section] with wrong URLs

### ISSUE THREAD

**Issue by lealog** [uperf/uperf#39]
Hi,

I don't know if I'm opening this issue in the right place :/
I was reading the http://uperf.org/ and realise that all URLs on BLOGS section are not working.

![image](https://user-images.githubusercontent.com/41795438/101555762-2eacc000-39b1-11eb-821c-0e920eb48901.png)

All these blogs are pointing to https://blogs.oracle.com/xxxxx. None of the blogs are working now.
Can you fix it

**Comment by realneel** [comment]
Sorry for the late response. I fixed the URLs
