### ISSUE TITLE
ERROR - no such file or directory: ./uperf

### ISSUE THREAD

**Issue by lealog** [uperf/uperf#41]
Hi,

I'm using kali linux

> uname -a
> Linux` kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux

After compile uperf with no errors, I'm trying to start uperf as slave but I'm receiving the following error:

> ./uperf -s                                                                                       
> zsh: no such file or directory: ./uperf

Can you please help to overcome this issue?

**Comment by realneel** [comment]
does `./src/uperf s` work?

**Comment by lealog** [comment]
Yes. Thanks :) Does it make sense to update the documentation?
